input("What's your name?: ")

#myName = input("Enter your name: ")
#myAge = input("Enter your age: ")
#print(myName)
#print(myAge)
#replit = input("Do you like Replit? : ")
#print(replit)
print("Getting to know you!")
yourName = input("What's your name? : ")
favFood = input("What's your favourite food? : ")
favMusic = input("What's your favourite music? : ")
yourLive = input("Where do you live? : ")
print("You are : Mark \n You're probably hungry for\n  Burritos\n  My man, Rick Astley \n living in the amazing \n California ")